name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0' # Postavite odgovarajuću verziju Node.js-a

      - name: Install Ionic CLI
        run: npm install --save-dev @ionic/cli
      - name: Build
        run: |
         npx ionic build --prod
      - name: Copy .well-known directory
        run: |
          cp -R src/.well-known www/.well-known  # Kopiranje .well-known direktorija u www direktorij
      - name: Copy staticwebapp.config.json to www folder
        run: |
         cp staticwebapp.config.json www/staticwebapp.config.json 
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_GRASS_0AED0AB03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "www" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "www/" # Built app content directory - optional
          config_file_location: "www"
          verbose: true
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_GRASS_0AED0AB03 }}
          action: "close"
